#!/bin/sh
# File generated by ocamlbuild

cd /home/a7qlf/Documents/CHARBON/4A/Ocaml_projet/_build

rm -f ftest.cmx
rm -f ftest.ml.depends
rm -f ftest.o
rm -f gfile.cmx
rm -f gfile.ml.depends
rm -f gfile.mli.depends
rm -f gfile.o
rm -f graph.cmx
rm -f graph.ml.depends
rm -f graph.mli.depends
rm -f graph.o
# Also clean the script itself
rm -f /home/a7qlf/Documents/CHARBON/4A/Ocaml_projet/_build/_build/sanitize.sh
